const sb=window.supabaseClient||window.supabase?.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let products=[],stores=[],categories=["All"],followedStores=[],currentUser=null,currentMyStore=null,currentCategory="All",authMode="login";
const $=id=>document.getElementById(id),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),money=v=>"৳"+Number(v||0).toLocaleString("en-BD",{maximumFractionDigits:2});
function toast(m){let x=$("toast");x.textContent=m;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),2400)}
function go(p){location.hash="#"+p;closeMenu()}function route(){let p=(location.hash||"#home").slice(1).split("?")[0];if(!["home","following","add-product","chat","my-store","product-detail"].includes(p))p="home";document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active-page",x.id===p));document.querySelectorAll(".bottom button").forEach(x=>x.classList.toggle("active",x.dataset.route===p));if(p==="home")renderProducts(currentCategory,$("searchInput")?.value||"");if(p==="following")renderFollowing();if(p==="my-store")renderMyStore();window.scrollTo(0,0)}
window.addEventListener("hashchange",route);
async function loadStores(){if(!sb)return;let{data,error}=await sb.from("stores").select("id,name,slug,logo_url,cover_url,description,is_active,is_approved,owner_id,created_at").eq("is_active",true).eq("is_approved",true).order("created_at",{ascending:false});if(error){console.error(error);stores=[]}else stores=data||[]}
async function loadProducts(){if(!sb)return;let{data,error}=await sb.from("products").select("id,name,price,description,stock,category_id,store_id,image_url,is_active,is_approved,created_at,categories(name),stores(id,name,slug,is_active,is_approved)").eq("is_active",true).eq("is_approved",true).order("created_at",{ascending:false});if(error){console.error(error);products=[];renderProducts();return}products=(data||[]).map(p=>({id:p.id,name:p.name,price:Number(p.price),description:p.description||"",stock:Number(p.stock||0),category:p.categories?.name||"Others",store:p.stores?.name||"Unknown Store",storeSlug:p.stores?.slug||"",storeId:p.store_id,image:p.image_url||null}));renderProducts(currentCategory,$("searchInput")?.value||"")}
function storeHTML(s){return `<div class="store-result"><div class="avatar">${s.logo_url?`<img class="avatar" src="${esc(s.logo_url)}">`:""}</div><div class="store-result-info"><strong>${esc(s.name)}</strong><span class="store-meta">@${esc(s.slug)}</span></div><button class="view-store" data-id="${esc(s.id)}">View Store</button></div>`}
function renderProducts(cat="All",query=""){currentCategory=cat;let q=String(query).trim().toLowerCase(),clean=q.replace(/^@/,"");let ps=products.filter(p=>(cat==="All"||p.category===cat)&&(!q||`${p.name} ${p.store} ${p.storeSlug} ${p.category} ${p.description}`.toLowerCase().includes(q)));let ss=q?stores.filter(s=>String(s.name).toLowerCase().includes(q)||String(s.slug).toLowerCase().includes(clean)).slice(0,8):[];let box=$("products");$("productCount").textContent=ps.length+" products";if(!ps.length&&!ss.length){box.innerHTML='<div class="empty">কোনো Product বা Store পাওয়া যায়নি।</div>';return}box.innerHTML=(ss.length?`<div class="store-search-results"><h2>Stores</h2>${ss.map(storeHTML).join("")}</div>`:"")+ps.map(p=>`<article class="product-card" data-id="${esc(p.id)}">${p.image?`<img class="product-image" src="${esc(p.image)}">`:'<div class="product-image"></div>'}<div class="product-info"><div class="product-name">${esc(p.name)}</div><div class="price">${money(p.price)}</div><div class="store-name">${esc(p.store)}</div></div></article>`).join("");box.querySelectorAll(".product-card").forEach(x=>x.onclick=()=>openProduct(x.dataset.id));box.querySelectorAll(".view-store").forEach(x=>x.onclick=e=>{e.stopPropagation();let s=stores.find(z=>String(z.id)===String(x.dataset.id));if(s){$("searchInput").value=s.name;renderProducts("All",s.name)}})}
function openProduct(id){let p=products.find(x=>String(x.id)===String(id));if(!p)return;$("productDetailContent").innerHTML=`<button class="secondary" onclick="go('home')">← Back</button><div class="detail">${p.image?`<img src="${esc(p.image)}">`:""}<div class="detail-body"><h1>${esc(p.name)}</h1><h2>${money(p.price)}</h2><p><b>Store:</b> ${esc(p.store)}</p><p><b>Stock:</b> ${p.stock}</p><p>${esc(p.description)}</p><button class="primary" onclick="toast('Order system পরের ধাপে যোগ করা যাবে')">Buy / Order</button></div></div>`;go("product-detail")}
async function loadCategories(){if(!sb)return;let{data,error}=await sb.from("categories").select("id,name").order("name");categories=error?["All"]:["All",...(data||[]).map(x=>x.name)];renderCategories();populateCategory()}
function renderCategories(){let b=$("categories");b.innerHTML=categories.map(x=>`<button class="category ${x===currentCategory?"active":""}" data-cat="${esc(x)}">${esc(x)}</button>`).join("");b.querySelectorAll(".category").forEach(x=>x.onclick=()=>{currentCategory=x.dataset.cat;renderCategories();renderProducts(currentCategory,$("searchInput").value)})}
function populateCategory(){$("productCategory").innerHTML=categories.filter(x=>x!=="All").map(x=>`<option>${esc(x)}</option>`).join("")}
async function updateAuth(){if(!sb)return;let{data}=await sb.auth.getSession();currentUser=data?.session?.user||null;await loadMyStore();await loadFollowing();updateAccount()}
async function loadMyStore(){currentMyStore=null;if(!currentUser)return;let{data,error}=await sb.from("stores").select("*").eq("owner_id",currentUser.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!error)currentMyStore=data||null}
async function loadFollowing(){followedStores=[];if(!currentUser)return;let{data,error}=await sb.from("followed_stores").select("store_id,stores(id,name,slug,logo_url,description)").eq("user_id",currentUser.id);if(!error)followedStores=(data||[]).map(x=>x.stores).filter(Boolean)}
function updateAccount(){if(!currentUser){$("accountStatus").innerHTML='<div class="card"><b>Guest user</b><br><span class="store-meta">Login করলে Store management ব্যবহার করতে পারবে।</span></div>';$("loginBtn").classList.remove("hidden");$("logoutBtn").classList.add("hidden");$("createStoreBtn").classList.add("hidden");return}$("accountStatus").innerHTML=`<div class="card"><b>${esc(currentUser.email)}</b><br><span class="store-meta">Logged in</span></div>`;$("loginBtn").classList.add("hidden");$("logoutBtn").classList.remove("hidden");$("createStoreBtn").classList.toggle("hidden",!!currentMyStore)}
function openAuth(m="login"){authMode=m;$("authTitle").textContent=m==="login"?"Login":"Create account";$("authSubtitle").textContent=m==="login"?"তোমার BuyHaat account-এ login করো।":"নতুন BuyHaat account তৈরি করো।";$("authSubmitBtn").textContent=m==="login"?"Login":"Register";$("authSwitchBtn").textContent=m==="login"?"নতুন অ্যাকাউন্ট তৈরি করুন":"আগের অ্যাকাউন্টে Login করুন";$("authMessage").textContent="";$("authModal").classList.remove("hidden")}function closeAuth(){$("authModal").classList.add("hidden")}
async function authSubmit(e){e.preventDefault();let r=authMode==="login"?await sb.auth.signInWithPassword({email:$("authEmail").value.trim(),password:$("authPassword").value}):await sb.auth.signUp({email:$("authEmail").value.trim(),password:$("authPassword").value});if(r.error){$("authMessage").textContent=r.error.message;return}if(authMode==="register"&&!r.data?.session){$("authMessage").textContent="Account তৈরি হয়েছে। Email confirmation লাগলে verify করে Login করো।";return}closeAuth();await updateAuth();toast("Success");route()}
async function logout(){let{error}=await sb.auth.signOut();if(error)return toast(error.message);currentUser=null;currentMyStore=null;updateAccount();go("home")}
function openStore(){$("storeMessage").textContent="";$("storeModal").classList.remove("hidden")}function closeStore(){$("storeModal").classList.add("hidden")}
async function createStore(e){e.preventDefault();if(!currentUser)return openAuth();let name=$("storeName").value.trim(),base=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,""),slug=`${base||"store"}-${Math.random().toString(36).slice(2,8)}`;let{data,error}=await sb.from("stores").insert({owner_id:currentUser.id,name,slug,description:$("storeDescription").value.trim()||null,phone:$("storePhone").value.trim()||null,address:$("storeAddress").value.trim()||null,logo_url:$("storeLogoUrl").value.trim()||null,cover_url:$("storeCoverUrl").value.trim()||null,is_active:true,is_approved:false}).select().single();if(error){$("storeMessage").textContent=error.message;return}currentMyStore=data;closeStore();updateAccount();renderMyStore();toast("Store created — approval pending")}
async function addProduct(e){e.preventDefault();if(!currentUser)return openAuth();if(!currentMyStore)return openStore();let{data:cat}=await sb.from("categories").select("id").eq("name",$("productCategory").value).maybeSingle();if(!cat)return $("productMsg").textContent="Category পাওয়া যায়নি।";let{error}=await sb.from("products").insert({name:$("productName").value.trim(),price:Number($("productPrice").value),description:$("productDescription").value.trim()||null,stock:Number($("productStock").value),category_id:cat.id,store_id:currentMyStore.id,image_url:$("productImageUrl").value.trim()||null,is_active:true,is_approved:false});if(error){$("productMsg").textContent=error.message;return}$("productForm").reset();$("productStock").value=1;$("productMsg").textContent="Product added — approval pending.";await loadProducts();renderMyStore()}
function renderFollowing(){let b=$("followingList");if(!currentUser)return b.innerHTML='<div class="empty">Following দেখতে Login করো।</div>';if(!followedStores.length)return b.innerHTML='<div class="empty">এখনো কোনো Store follow করোনি।</div>';b.innerHTML=followedStores.map(s=>`<div class="store-card"><div class="avatar"></div><div><b>${esc(s.name)}</b><br><span class="store-meta">@${esc(s.slug)}</span></div></div>`).join("")}
async function renderMyStore(){updateAccount();let b=$("myStoreContent"),m=$("storeManagerCard");if(!currentUser){b.innerHTML='<div class="empty">My Store ব্যবহার করতে Login করো।</div>';m.classList.add("hidden");return}if(!currentMyStore){b.innerHTML='<div class="empty">তোমার Store নেই। Create Store চাপো।</div>';m.classList.add("hidden");return}let s=currentMyStore;b.innerHTML=`<div class="card"><h2>${esc(s.name)}</h2><p>@${esc(s.slug)}</p><p>${esc(s.description||"No description")}</p><small>${s.is_approved?"Approved":"Pending approval"}</small></div>`;m.classList.remove("hidden");await sellerProducts();await sellerOrders();sellerSettings()}
async function sellerProducts(){let b=$("sellerProductsTab");let{data,error}=await sb.from("products").select("id,name,price,stock,image_url,is_approved").eq("store_id",currentMyStore.id).order("created_at",{ascending:false});if(error)return b.innerHTML=`<div class="empty">${esc(error.message)}</div>`;b.innerHTML=data?.length?data.map(p=>`<div class="manage">${p.image_url?`<img src="${esc(p.image_url)}">`:""}<div class="manage-info"><b>${esc(p.name)}</b><br><small>${money(p.price)} · Stock ${p.stock} · ${p.is_approved?"Approved":"Pending"}</small></div><button class="small edit" data-id="${p.id}">Edit</button><button class="small del" data-id="${p.id}">Delete</button></div>`).join(""):'<div class="empty">কোনো product নেই।</div>';b.querySelectorAll(".edit").forEach(x=>x.onclick=()=>editProduct(x.dataset.id));b.querySelectorAll(".del").forEach(x=>x.onclick=()=>deleteProduct(x.dataset.id))}
async function editProduct(id){let{data,error}=await sb.from("products").select("*").eq("id",id).eq("store_id",currentMyStore.id).single();if(error)return toast(error.message);let name=prompt("Product name",data.name),price=prompt("Price",data.price),stock=prompt("Stock",data.stock);if(name===null||price===null||stock===null)return;let{error:e}=await sb.from("products").update({name:name.trim(),price:Number(price),stock:Number(stock)}).eq("id",id).eq("store_id",currentMyStore.id);if(e)return toast(e.message);await loadProducts();await sellerProducts();toast("Product updated")}
async function deleteProduct(id){if(!confirm("এই product remove করতে চাও?"))return;let{error}=await sb.from("products").update({is_active:false}).eq("id",id).eq("store_id",currentMyStore.id);if(error)return toast(error.message);await loadProducts();await sellerProducts();toast("Product removed")}
async function sellerOrders(){let b=$("sellerOrdersTab");let{data,error}=await sb.from("order_items").select("id,order_id,quantity,price,products!inner(id,name,store_id),orders(id,status,created_at,total_amount)").eq("products.store_id",currentMyStore.id).order("created_at",{ascending:false});if(error)return b.innerHTML=`<div class="empty">${esc(error.message)}</div>`;b.innerHTML=data?.length?data.map(x=>`<div class="card"><b>Order #${esc(x.order_id)}</b><p>${esc(x.products?.name||"Product")} × ${x.quantity}</p><small>Status: ${esc(x.orders?.status||"pending")}</small></div>`).join(""):'<div class="empty">কোনো order নেই।</div>'}
function sellerSettings(){let b=$("sellerSettingsTab");b.innerHTML=`<div class="card"><label>Store name<input id="setName" value="${esc(currentMyStore.name)}"></label><label>Description<textarea id="setDesc">${esc(currentMyStore.description||"")}</textarea></label><label>Phone<input id="setPhone" value="${esc(currentMyStore.phone||"")}"></label><label>Address<input id="setAddress" value="${esc(currentMyStore.address||"")}"></label><button id="saveStore" class="primary">Save Store</button></div>`;$("saveStore").onclick=async()=>{let{data,error}=await sb.from("stores").update({name:$("setName").value.trim(),description:$("setDesc").value.trim()||null,phone:$("setPhone").value.trim()||null,address:$("setAddress").value.trim()||null}).eq("id",currentMyStore.id).eq("owner_id",currentUser.id).select().single();if(error)return toast(error.message);currentMyStore=data;await loadStores();renderMyStore();toast("Store updated")}}
function init(){document.querySelectorAll("[data-route]").forEach(x=>x.onclick=()=>go(x.dataset.route));$("menuBtn").onclick=()=>$("sideMenu").classList.add("open");$("closeMenuBtn").onclick=closeMenu;$("menuOverlay").onclick=closeMenu;$("loginBtn").onclick=()=>openAuth();$("logoutBtn").onclick=logout;$("createStoreBtn").onclick=openStore;$("closeAuthBtn").onclick=closeAuth;$("authSwitchBtn").onclick=()=>openAuth(authMode==="login"?"register":"login");$("authForm").onsubmit=authSubmit;$("closeStoreBtn").onclick=closeStore;$("storeForm").onsubmit=createStore;$("productForm").onsubmit=addProduct;$("searchInput").oninput=()=>renderProducts(currentCategory,$("searchInput").value);$("searchBtn").onclick=()=>{go("home");renderProducts(currentCategory,$("searchInput").value)};$("headerSearchBtn").onclick=()=>{go("home");$("searchInput").focus()};document.querySelectorAll(".tab").forEach(x=>x.onclick=()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));x.classList.add("active");["products","orders","settings"].forEach(t=>$("seller"+t[0].toUpperCase()+t.slice(1)+"Tab").classList.toggle("hidden",t!==x.dataset.tab))});renderCategories();renderProducts();route();(async()=>{await updateAuth();await loadCategories();await loadStores();await loadProducts();route()})()}
if(sb?.auth)sb.auth.onAuthStateChange(async()=>{await updateAuth();if(location.hash==="#my-store")renderMyStore()});document.addEventListener("DOMContentLoaded",init);
window.go=go;window.toast=toast;